# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jh/clion-2016.3.4/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/jh/clion-2016.3.4/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jh/ssvo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jh/ssvo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/jh/clion-2016.3.4/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/jh/clion-2016.3.4/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jh/ssvo/CMakeFiles /home/jh/ssvo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jh/ssvo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_dbow3

# Build rule for target.
test_dbow3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dbow3
.PHONY : test_dbow3

# fast build rule for target.
test_dbow3/fast:
	$(MAKE) -f CMakeFiles/test_dbow3.dir/build.make CMakeFiles/test_dbow3.dir/build
.PHONY : test_dbow3/fast

#=============================================================================
# Target rules for targets named test_timer

# Build rule for target.
test_timer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_timer
.PHONY : test_timer

# fast build rule for target.
test_timer/fast:
	$(MAKE) -f CMakeFiles/test_timer.dir/build.make CMakeFiles/test_timer.dir/build
.PHONY : test_timer/fast

#=============================================================================
# Target rules for targets named test_camera_model

# Build rule for target.
test_camera_model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_camera_model
.PHONY : test_camera_model

# fast build rule for target.
test_camera_model/fast:
	$(MAKE) -f CMakeFiles/test_camera_model.dir/build.make CMakeFiles/test_camera_model.dir/build
.PHONY : test_camera_model/fast

#=============================================================================
# Target rules for targets named test_alignment_2d

# Build rule for target.
test_alignment_2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_alignment_2d
.PHONY : test_alignment_2d

# fast build rule for target.
test_alignment_2d/fast:
	$(MAKE) -f CMakeFiles/test_alignment_2d.dir/build.make CMakeFiles/test_alignment_2d.dir/build
.PHONY : test_alignment_2d/fast

#=============================================================================
# Target rules for targets named ssvo

# Build rule for target.
ssvo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssvo
.PHONY : ssvo

# fast build rule for target.
ssvo/fast:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/build
.PHONY : ssvo/fast

#=============================================================================
# Target rules for targets named test_alignment

# Build rule for target.
test_alignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_alignment
.PHONY : test_alignment

# fast build rule for target.
test_alignment/fast:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/build
.PHONY : test_alignment/fast

#=============================================================================
# Target rules for targets named test_pattern

# Build rule for target.
test_pattern: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pattern
.PHONY : test_pattern

# fast build rule for target.
test_pattern/fast:
	$(MAKE) -f CMakeFiles/test_pattern.dir/build.make CMakeFiles/test_pattern.dir/build
.PHONY : test_pattern/fast

#=============================================================================
# Target rules for targets named test_feature_detector

# Build rule for target.
test_feature_detector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_feature_detector
.PHONY : test_feature_detector

# fast build rule for target.
test_feature_detector/fast:
	$(MAKE) -f CMakeFiles/test_feature_detector.dir/build.make CMakeFiles/test_feature_detector.dir/build
.PHONY : test_feature_detector/fast

#=============================================================================
# Target rules for targets named test_utils

# Build rule for target.
test_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_utils
.PHONY : test_utils

# fast build rule for target.
test_utils/fast:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/build
.PHONY : test_utils/fast

#=============================================================================
# Target rules for targets named test_initializer_seq

# Build rule for target.
test_initializer_seq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_initializer_seq
.PHONY : test_initializer_seq

# fast build rule for target.
test_initializer_seq/fast:
	$(MAKE) -f CMakeFiles/test_initializer_seq.dir/build.make CMakeFiles/test_initializer_seq.dir/build
.PHONY : test_initializer_seq/fast

#=============================================================================
# Target rules for targets named test_glog

# Build rule for target.
test_glog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_glog
.PHONY : test_glog

# fast build rule for target.
test_glog/fast:
	$(MAKE) -f CMakeFiles/test_glog.dir/build.make CMakeFiles/test_glog.dir/build
.PHONY : test_glog/fast

#=============================================================================
# Target rules for targets named monoVO_dataset

# Build rule for target.
monoVO_dataset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monoVO_dataset
.PHONY : monoVO_dataset

# fast build rule for target.
monoVO_dataset/fast:
	$(MAKE) -f CMakeFiles/monoVO_dataset.dir/build.make CMakeFiles/monoVO_dataset.dir/build
.PHONY : monoVO_dataset/fast

#=============================================================================
# Target rules for targets named test_triangulation

# Build rule for target.
test_triangulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_triangulation
.PHONY : test_triangulation

# fast build rule for target.
test_triangulation/fast:
	$(MAKE) -f CMakeFiles/test_triangulation.dir/build.make CMakeFiles/test_triangulation.dir/build
.PHONY : test_triangulation/fast

#=============================================================================
# Target rules for targets named monoVO_live

# Build rule for target.
monoVO_live: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monoVO_live
.PHONY : monoVO_live

# fast build rule for target.
monoVO_live/fast:
	$(MAKE) -f CMakeFiles/monoVO_live.dir/build.make CMakeFiles/monoVO_live.dir/build
.PHONY : monoVO_live/fast

#=============================================================================
# Target rules for targets named test_optimizer

# Build rule for target.
test_optimizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_optimizer
.PHONY : test_optimizer

# fast build rule for target.
test_optimizer/fast:
	$(MAKE) -f CMakeFiles/test_optimizer.dir/build.make CMakeFiles/test_optimizer.dir/build
.PHONY : test_optimizer/fast

demo/monoVO_dataset.o: demo/monoVO_dataset.cpp.o

.PHONY : demo/monoVO_dataset.o

# target to build an object file
demo/monoVO_dataset.cpp.o:
	$(MAKE) -f CMakeFiles/monoVO_dataset.dir/build.make CMakeFiles/monoVO_dataset.dir/demo/monoVO_dataset.cpp.o
.PHONY : demo/monoVO_dataset.cpp.o

demo/monoVO_dataset.i: demo/monoVO_dataset.cpp.i

.PHONY : demo/monoVO_dataset.i

# target to preprocess a source file
demo/monoVO_dataset.cpp.i:
	$(MAKE) -f CMakeFiles/monoVO_dataset.dir/build.make CMakeFiles/monoVO_dataset.dir/demo/monoVO_dataset.cpp.i
.PHONY : demo/monoVO_dataset.cpp.i

demo/monoVO_dataset.s: demo/monoVO_dataset.cpp.s

.PHONY : demo/monoVO_dataset.s

# target to generate assembly for a file
demo/monoVO_dataset.cpp.s:
	$(MAKE) -f CMakeFiles/monoVO_dataset.dir/build.make CMakeFiles/monoVO_dataset.dir/demo/monoVO_dataset.cpp.s
.PHONY : demo/monoVO_dataset.cpp.s

demo/monoVO_live.o: demo/monoVO_live.cpp.o

.PHONY : demo/monoVO_live.o

# target to build an object file
demo/monoVO_live.cpp.o:
	$(MAKE) -f CMakeFiles/monoVO_live.dir/build.make CMakeFiles/monoVO_live.dir/demo/monoVO_live.cpp.o
.PHONY : demo/monoVO_live.cpp.o

demo/monoVO_live.i: demo/monoVO_live.cpp.i

.PHONY : demo/monoVO_live.i

# target to preprocess a source file
demo/monoVO_live.cpp.i:
	$(MAKE) -f CMakeFiles/monoVO_live.dir/build.make CMakeFiles/monoVO_live.dir/demo/monoVO_live.cpp.i
.PHONY : demo/monoVO_live.cpp.i

demo/monoVO_live.s: demo/monoVO_live.cpp.s

.PHONY : demo/monoVO_live.s

# target to generate assembly for a file
demo/monoVO_live.cpp.s:
	$(MAKE) -f CMakeFiles/monoVO_live.dir/build.make CMakeFiles/monoVO_live.dir/demo/monoVO_live.cpp.s
.PHONY : demo/monoVO_live.cpp.s

src/brief.o: src/brief.cpp.o

.PHONY : src/brief.o

# target to build an object file
src/brief.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/brief.cpp.o
.PHONY : src/brief.cpp.o

src/brief.i: src/brief.cpp.i

.PHONY : src/brief.i

# target to preprocess a source file
src/brief.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/brief.cpp.i
.PHONY : src/brief.cpp.i

src/brief.s: src/brief.cpp.s

.PHONY : src/brief.s

# target to generate assembly for a file
src/brief.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/brief.cpp.s
.PHONY : src/brief.cpp.s

src/camera.o: src/camera.cpp.o

.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) -f CMakeFiles/test_camera_model.dir/build.make CMakeFiles/test_camera_model.dir/src/camera.cpp.o
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i

.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) -f CMakeFiles/test_camera_model.dir/build.make CMakeFiles/test_camera_model.dir/src/camera.cpp.i
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s

.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) -f CMakeFiles/test_camera_model.dir/build.make CMakeFiles/test_camera_model.dir/src/camera.cpp.s
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/depth_filter.o: src/depth_filter.cpp.o

.PHONY : src/depth_filter.o

# target to build an object file
src/depth_filter.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/depth_filter.cpp.o
.PHONY : src/depth_filter.cpp.o

src/depth_filter.i: src/depth_filter.cpp.i

.PHONY : src/depth_filter.i

# target to preprocess a source file
src/depth_filter.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/depth_filter.cpp.i
.PHONY : src/depth_filter.cpp.i

src/depth_filter.s: src/depth_filter.cpp.s

.PHONY : src/depth_filter.s

# target to generate assembly for a file
src/depth_filter.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/depth_filter.cpp.s
.PHONY : src/depth_filter.cpp.s

src/feature_alignment.o: src/feature_alignment.cpp.o

.PHONY : src/feature_alignment.o

# target to build an object file
src/feature_alignment.cpp.o:
	$(MAKE) -f CMakeFiles/test_alignment_2d.dir/build.make CMakeFiles/test_alignment_2d.dir/src/feature_alignment.cpp.o
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_alignment.cpp.o
.PHONY : src/feature_alignment.cpp.o

src/feature_alignment.i: src/feature_alignment.cpp.i

.PHONY : src/feature_alignment.i

# target to preprocess a source file
src/feature_alignment.cpp.i:
	$(MAKE) -f CMakeFiles/test_alignment_2d.dir/build.make CMakeFiles/test_alignment_2d.dir/src/feature_alignment.cpp.i
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_alignment.cpp.i
.PHONY : src/feature_alignment.cpp.i

src/feature_alignment.s: src/feature_alignment.cpp.s

.PHONY : src/feature_alignment.s

# target to generate assembly for a file
src/feature_alignment.cpp.s:
	$(MAKE) -f CMakeFiles/test_alignment_2d.dir/build.make CMakeFiles/test_alignment_2d.dir/src/feature_alignment.cpp.s
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_alignment.cpp.s
.PHONY : src/feature_alignment.cpp.s

src/feature_detector.o: src/feature_detector.cpp.o

.PHONY : src/feature_detector.o

# target to build an object file
src/feature_detector.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_detector.cpp.o
.PHONY : src/feature_detector.cpp.o

src/feature_detector.i: src/feature_detector.cpp.i

.PHONY : src/feature_detector.i

# target to preprocess a source file
src/feature_detector.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_detector.cpp.i
.PHONY : src/feature_detector.cpp.i

src/feature_detector.s: src/feature_detector.cpp.s

.PHONY : src/feature_detector.s

# target to generate assembly for a file
src/feature_detector.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_detector.cpp.s
.PHONY : src/feature_detector.cpp.s

src/feature_tracker.o: src/feature_tracker.cpp.o

.PHONY : src/feature_tracker.o

# target to build an object file
src/feature_tracker.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_tracker.cpp.o
.PHONY : src/feature_tracker.cpp.o

src/feature_tracker.i: src/feature_tracker.cpp.i

.PHONY : src/feature_tracker.i

# target to preprocess a source file
src/feature_tracker.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_tracker.cpp.i
.PHONY : src/feature_tracker.cpp.i

src/feature_tracker.s: src/feature_tracker.cpp.s

.PHONY : src/feature_tracker.s

# target to generate assembly for a file
src/feature_tracker.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/feature_tracker.cpp.s
.PHONY : src/feature_tracker.cpp.s

src/frame.o: src/frame.cpp.o

.PHONY : src/frame.o

# target to build an object file
src/frame.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/frame.cpp.o
.PHONY : src/frame.cpp.o

src/frame.i: src/frame.cpp.i

.PHONY : src/frame.i

# target to preprocess a source file
src/frame.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/frame.cpp.i
.PHONY : src/frame.cpp.i

src/frame.s: src/frame.cpp.s

.PHONY : src/frame.s

# target to generate assembly for a file
src/frame.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/frame.cpp.s
.PHONY : src/frame.cpp.s

src/image_alignment.o: src/image_alignment.cpp.o

.PHONY : src/image_alignment.o

# target to build an object file
src/image_alignment.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/image_alignment.cpp.o
.PHONY : src/image_alignment.cpp.o

src/image_alignment.i: src/image_alignment.cpp.i

.PHONY : src/image_alignment.i

# target to preprocess a source file
src/image_alignment.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/image_alignment.cpp.i
.PHONY : src/image_alignment.cpp.i

src/image_alignment.s: src/image_alignment.cpp.s

.PHONY : src/image_alignment.s

# target to generate assembly for a file
src/image_alignment.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/image_alignment.cpp.s
.PHONY : src/image_alignment.cpp.s

src/initializer.o: src/initializer.cpp.o

.PHONY : src/initializer.o

# target to build an object file
src/initializer.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/initializer.cpp.o
	$(MAKE) -f CMakeFiles/test_initializer_seq.dir/build.make CMakeFiles/test_initializer_seq.dir/src/initializer.cpp.o
.PHONY : src/initializer.cpp.o

src/initializer.i: src/initializer.cpp.i

.PHONY : src/initializer.i

# target to preprocess a source file
src/initializer.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/initializer.cpp.i
	$(MAKE) -f CMakeFiles/test_initializer_seq.dir/build.make CMakeFiles/test_initializer_seq.dir/src/initializer.cpp.i
.PHONY : src/initializer.cpp.i

src/initializer.s: src/initializer.cpp.s

.PHONY : src/initializer.s

# target to generate assembly for a file
src/initializer.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/initializer.cpp.s
	$(MAKE) -f CMakeFiles/test_initializer_seq.dir/build.make CMakeFiles/test_initializer_seq.dir/src/initializer.cpp.s
.PHONY : src/initializer.cpp.s

src/keyframe.o: src/keyframe.cpp.o

.PHONY : src/keyframe.o

# target to build an object file
src/keyframe.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/keyframe.cpp.o
.PHONY : src/keyframe.cpp.o

src/keyframe.i: src/keyframe.cpp.i

.PHONY : src/keyframe.i

# target to preprocess a source file
src/keyframe.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/keyframe.cpp.i
.PHONY : src/keyframe.cpp.i

src/keyframe.s: src/keyframe.cpp.s

.PHONY : src/keyframe.s

# target to generate assembly for a file
src/keyframe.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/keyframe.cpp.s
.PHONY : src/keyframe.cpp.s

src/local_mapping.o: src/local_mapping.cpp.o

.PHONY : src/local_mapping.o

# target to build an object file
src/local_mapping.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/local_mapping.cpp.o
.PHONY : src/local_mapping.cpp.o

src/local_mapping.i: src/local_mapping.cpp.i

.PHONY : src/local_mapping.i

# target to preprocess a source file
src/local_mapping.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/local_mapping.cpp.i
.PHONY : src/local_mapping.cpp.i

src/local_mapping.s: src/local_mapping.cpp.s

.PHONY : src/local_mapping.s

# target to generate assembly for a file
src/local_mapping.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/local_mapping.cpp.s
.PHONY : src/local_mapping.cpp.s

src/map.o: src/map.cpp.o

.PHONY : src/map.o

# target to build an object file
src/map.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/map.cpp.o
.PHONY : src/map.cpp.o

src/map.i: src/map.cpp.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/map.cpp.i
.PHONY : src/map.cpp.i

src/map.s: src/map.cpp.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/map.cpp.s
.PHONY : src/map.cpp.s

src/map_point.o: src/map_point.cpp.o

.PHONY : src/map_point.o

# target to build an object file
src/map_point.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/map_point.cpp.o
.PHONY : src/map_point.cpp.o

src/map_point.i: src/map_point.cpp.i

.PHONY : src/map_point.i

# target to preprocess a source file
src/map_point.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/map_point.cpp.i
.PHONY : src/map_point.cpp.i

src/map_point.s: src/map_point.cpp.s

.PHONY : src/map_point.s

# target to generate assembly for a file
src/map_point.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/map_point.cpp.s
.PHONY : src/map_point.cpp.s

src/optimizer.o: src/optimizer.cpp.o

.PHONY : src/optimizer.o

# target to build an object file
src/optimizer.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/optimizer.cpp.o
.PHONY : src/optimizer.cpp.o

src/optimizer.i: src/optimizer.cpp.i

.PHONY : src/optimizer.i

# target to preprocess a source file
src/optimizer.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/optimizer.cpp.i
.PHONY : src/optimizer.cpp.i

src/optimizer.s: src/optimizer.cpp.s

.PHONY : src/optimizer.s

# target to generate assembly for a file
src/optimizer.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/optimizer.cpp.s
.PHONY : src/optimizer.cpp.s

src/seed.o: src/seed.cpp.o

.PHONY : src/seed.o

# target to build an object file
src/seed.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/seed.cpp.o
.PHONY : src/seed.cpp.o

src/seed.i: src/seed.cpp.i

.PHONY : src/seed.i

# target to preprocess a source file
src/seed.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/seed.cpp.i
.PHONY : src/seed.cpp.i

src/seed.s: src/seed.cpp.s

.PHONY : src/seed.s

# target to generate assembly for a file
src/seed.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/seed.cpp.s
.PHONY : src/seed.cpp.s

src/system.o: src/system.cpp.o

.PHONY : src/system.o

# target to build an object file
src/system.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/system.cpp.o
.PHONY : src/system.cpp.o

src/system.i: src/system.cpp.i

.PHONY : src/system.i

# target to preprocess a source file
src/system.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/system.cpp.i
.PHONY : src/system.cpp.i

src/system.s: src/system.cpp.s

.PHONY : src/system.s

# target to generate assembly for a file
src/system.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/system.cpp.s
.PHONY : src/system.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/viewer.o: src/viewer.cpp.o

.PHONY : src/viewer.o

# target to build an object file
src/viewer.cpp.o:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/viewer.cpp.o
.PHONY : src/viewer.cpp.o

src/viewer.i: src/viewer.cpp.i

.PHONY : src/viewer.i

# target to preprocess a source file
src/viewer.cpp.i:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/viewer.cpp.i
.PHONY : src/viewer.cpp.i

src/viewer.s: src/viewer.cpp.s

.PHONY : src/viewer.s

# target to generate assembly for a file
src/viewer.cpp.s:
	$(MAKE) -f CMakeFiles/ssvo.dir/build.make CMakeFiles/ssvo.dir/src/viewer.cpp.s
.PHONY : src/viewer.cpp.s

test/test_alignment.o: test/test_alignment.cpp.o

.PHONY : test/test_alignment.o

# target to build an object file
test/test_alignment.cpp.o:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/test/test_alignment.cpp.o
.PHONY : test/test_alignment.cpp.o

test/test_alignment.i: test/test_alignment.cpp.i

.PHONY : test/test_alignment.i

# target to preprocess a source file
test/test_alignment.cpp.i:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/test/test_alignment.cpp.i
.PHONY : test/test_alignment.cpp.i

test/test_alignment.s: test/test_alignment.cpp.s

.PHONY : test/test_alignment.s

# target to generate assembly for a file
test/test_alignment.cpp.s:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/test/test_alignment.cpp.s
.PHONY : test/test_alignment.cpp.s

test/test_alignment_2d.o: test/test_alignment_2d.cpp.o

.PHONY : test/test_alignment_2d.o

# target to build an object file
test/test_alignment_2d.cpp.o:
	$(MAKE) -f CMakeFiles/test_alignment_2d.dir/build.make CMakeFiles/test_alignment_2d.dir/test/test_alignment_2d.cpp.o
.PHONY : test/test_alignment_2d.cpp.o

test/test_alignment_2d.i: test/test_alignment_2d.cpp.i

.PHONY : test/test_alignment_2d.i

# target to preprocess a source file
test/test_alignment_2d.cpp.i:
	$(MAKE) -f CMakeFiles/test_alignment_2d.dir/build.make CMakeFiles/test_alignment_2d.dir/test/test_alignment_2d.cpp.i
.PHONY : test/test_alignment_2d.cpp.i

test/test_alignment_2d.s: test/test_alignment_2d.cpp.s

.PHONY : test/test_alignment_2d.s

# target to generate assembly for a file
test/test_alignment_2d.cpp.s:
	$(MAKE) -f CMakeFiles/test_alignment_2d.dir/build.make CMakeFiles/test_alignment_2d.dir/test/test_alignment_2d.cpp.s
.PHONY : test/test_alignment_2d.cpp.s

test/test_camera_model.o: test/test_camera_model.cpp.o

.PHONY : test/test_camera_model.o

# target to build an object file
test/test_camera_model.cpp.o:
	$(MAKE) -f CMakeFiles/test_camera_model.dir/build.make CMakeFiles/test_camera_model.dir/test/test_camera_model.cpp.o
.PHONY : test/test_camera_model.cpp.o

test/test_camera_model.i: test/test_camera_model.cpp.i

.PHONY : test/test_camera_model.i

# target to preprocess a source file
test/test_camera_model.cpp.i:
	$(MAKE) -f CMakeFiles/test_camera_model.dir/build.make CMakeFiles/test_camera_model.dir/test/test_camera_model.cpp.i
.PHONY : test/test_camera_model.cpp.i

test/test_camera_model.s: test/test_camera_model.cpp.s

.PHONY : test/test_camera_model.s

# target to generate assembly for a file
test/test_camera_model.cpp.s:
	$(MAKE) -f CMakeFiles/test_camera_model.dir/build.make CMakeFiles/test_camera_model.dir/test/test_camera_model.cpp.s
.PHONY : test/test_camera_model.cpp.s

test/test_dbow3.o: test/test_dbow3.cpp.o

.PHONY : test/test_dbow3.o

# target to build an object file
test/test_dbow3.cpp.o:
	$(MAKE) -f CMakeFiles/test_dbow3.dir/build.make CMakeFiles/test_dbow3.dir/test/test_dbow3.cpp.o
.PHONY : test/test_dbow3.cpp.o

test/test_dbow3.i: test/test_dbow3.cpp.i

.PHONY : test/test_dbow3.i

# target to preprocess a source file
test/test_dbow3.cpp.i:
	$(MAKE) -f CMakeFiles/test_dbow3.dir/build.make CMakeFiles/test_dbow3.dir/test/test_dbow3.cpp.i
.PHONY : test/test_dbow3.cpp.i

test/test_dbow3.s: test/test_dbow3.cpp.s

.PHONY : test/test_dbow3.s

# target to generate assembly for a file
test/test_dbow3.cpp.s:
	$(MAKE) -f CMakeFiles/test_dbow3.dir/build.make CMakeFiles/test_dbow3.dir/test/test_dbow3.cpp.s
.PHONY : test/test_dbow3.cpp.s

test/test_feature_detector.o: test/test_feature_detector.cpp.o

.PHONY : test/test_feature_detector.o

# target to build an object file
test/test_feature_detector.cpp.o:
	$(MAKE) -f CMakeFiles/test_feature_detector.dir/build.make CMakeFiles/test_feature_detector.dir/test/test_feature_detector.cpp.o
.PHONY : test/test_feature_detector.cpp.o

test/test_feature_detector.i: test/test_feature_detector.cpp.i

.PHONY : test/test_feature_detector.i

# target to preprocess a source file
test/test_feature_detector.cpp.i:
	$(MAKE) -f CMakeFiles/test_feature_detector.dir/build.make CMakeFiles/test_feature_detector.dir/test/test_feature_detector.cpp.i
.PHONY : test/test_feature_detector.cpp.i

test/test_feature_detector.s: test/test_feature_detector.cpp.s

.PHONY : test/test_feature_detector.s

# target to generate assembly for a file
test/test_feature_detector.cpp.s:
	$(MAKE) -f CMakeFiles/test_feature_detector.dir/build.make CMakeFiles/test_feature_detector.dir/test/test_feature_detector.cpp.s
.PHONY : test/test_feature_detector.cpp.s

test/test_glog.o: test/test_glog.cpp.o

.PHONY : test/test_glog.o

# target to build an object file
test/test_glog.cpp.o:
	$(MAKE) -f CMakeFiles/test_glog.dir/build.make CMakeFiles/test_glog.dir/test/test_glog.cpp.o
.PHONY : test/test_glog.cpp.o

test/test_glog.i: test/test_glog.cpp.i

.PHONY : test/test_glog.i

# target to preprocess a source file
test/test_glog.cpp.i:
	$(MAKE) -f CMakeFiles/test_glog.dir/build.make CMakeFiles/test_glog.dir/test/test_glog.cpp.i
.PHONY : test/test_glog.cpp.i

test/test_glog.s: test/test_glog.cpp.s

.PHONY : test/test_glog.s

# target to generate assembly for a file
test/test_glog.cpp.s:
	$(MAKE) -f CMakeFiles/test_glog.dir/build.make CMakeFiles/test_glog.dir/test/test_glog.cpp.s
.PHONY : test/test_glog.cpp.s

test/test_initializer_seq.o: test/test_initializer_seq.cpp.o

.PHONY : test/test_initializer_seq.o

# target to build an object file
test/test_initializer_seq.cpp.o:
	$(MAKE) -f CMakeFiles/test_initializer_seq.dir/build.make CMakeFiles/test_initializer_seq.dir/test/test_initializer_seq.cpp.o
.PHONY : test/test_initializer_seq.cpp.o

test/test_initializer_seq.i: test/test_initializer_seq.cpp.i

.PHONY : test/test_initializer_seq.i

# target to preprocess a source file
test/test_initializer_seq.cpp.i:
	$(MAKE) -f CMakeFiles/test_initializer_seq.dir/build.make CMakeFiles/test_initializer_seq.dir/test/test_initializer_seq.cpp.i
.PHONY : test/test_initializer_seq.cpp.i

test/test_initializer_seq.s: test/test_initializer_seq.cpp.s

.PHONY : test/test_initializer_seq.s

# target to generate assembly for a file
test/test_initializer_seq.cpp.s:
	$(MAKE) -f CMakeFiles/test_initializer_seq.dir/build.make CMakeFiles/test_initializer_seq.dir/test/test_initializer_seq.cpp.s
.PHONY : test/test_initializer_seq.cpp.s

test/test_optimizer.o: test/test_optimizer.cpp.o

.PHONY : test/test_optimizer.o

# target to build an object file
test/test_optimizer.cpp.o:
	$(MAKE) -f CMakeFiles/test_optimizer.dir/build.make CMakeFiles/test_optimizer.dir/test/test_optimizer.cpp.o
.PHONY : test/test_optimizer.cpp.o

test/test_optimizer.i: test/test_optimizer.cpp.i

.PHONY : test/test_optimizer.i

# target to preprocess a source file
test/test_optimizer.cpp.i:
	$(MAKE) -f CMakeFiles/test_optimizer.dir/build.make CMakeFiles/test_optimizer.dir/test/test_optimizer.cpp.i
.PHONY : test/test_optimizer.cpp.i

test/test_optimizer.s: test/test_optimizer.cpp.s

.PHONY : test/test_optimizer.s

# target to generate assembly for a file
test/test_optimizer.cpp.s:
	$(MAKE) -f CMakeFiles/test_optimizer.dir/build.make CMakeFiles/test_optimizer.dir/test/test_optimizer.cpp.s
.PHONY : test/test_optimizer.cpp.s

test/test_parttern.o: test/test_parttern.cpp.o

.PHONY : test/test_parttern.o

# target to build an object file
test/test_parttern.cpp.o:
	$(MAKE) -f CMakeFiles/test_pattern.dir/build.make CMakeFiles/test_pattern.dir/test/test_parttern.cpp.o
.PHONY : test/test_parttern.cpp.o

test/test_parttern.i: test/test_parttern.cpp.i

.PHONY : test/test_parttern.i

# target to preprocess a source file
test/test_parttern.cpp.i:
	$(MAKE) -f CMakeFiles/test_pattern.dir/build.make CMakeFiles/test_pattern.dir/test/test_parttern.cpp.i
.PHONY : test/test_parttern.cpp.i

test/test_parttern.s: test/test_parttern.cpp.s

.PHONY : test/test_parttern.s

# target to generate assembly for a file
test/test_parttern.cpp.s:
	$(MAKE) -f CMakeFiles/test_pattern.dir/build.make CMakeFiles/test_pattern.dir/test/test_parttern.cpp.s
.PHONY : test/test_parttern.cpp.s

test/test_timer.o: test/test_timer.cpp.o

.PHONY : test/test_timer.o

# target to build an object file
test/test_timer.cpp.o:
	$(MAKE) -f CMakeFiles/test_timer.dir/build.make CMakeFiles/test_timer.dir/test/test_timer.cpp.o
.PHONY : test/test_timer.cpp.o

test/test_timer.i: test/test_timer.cpp.i

.PHONY : test/test_timer.i

# target to preprocess a source file
test/test_timer.cpp.i:
	$(MAKE) -f CMakeFiles/test_timer.dir/build.make CMakeFiles/test_timer.dir/test/test_timer.cpp.i
.PHONY : test/test_timer.cpp.i

test/test_timer.s: test/test_timer.cpp.s

.PHONY : test/test_timer.s

# target to generate assembly for a file
test/test_timer.cpp.s:
	$(MAKE) -f CMakeFiles/test_timer.dir/build.make CMakeFiles/test_timer.dir/test/test_timer.cpp.s
.PHONY : test/test_timer.cpp.s

test/test_triangulation.o: test/test_triangulation.cpp.o

.PHONY : test/test_triangulation.o

# target to build an object file
test/test_triangulation.cpp.o:
	$(MAKE) -f CMakeFiles/test_triangulation.dir/build.make CMakeFiles/test_triangulation.dir/test/test_triangulation.cpp.o
.PHONY : test/test_triangulation.cpp.o

test/test_triangulation.i: test/test_triangulation.cpp.i

.PHONY : test/test_triangulation.i

# target to preprocess a source file
test/test_triangulation.cpp.i:
	$(MAKE) -f CMakeFiles/test_triangulation.dir/build.make CMakeFiles/test_triangulation.dir/test/test_triangulation.cpp.i
.PHONY : test/test_triangulation.cpp.i

test/test_triangulation.s: test/test_triangulation.cpp.s

.PHONY : test/test_triangulation.s

# target to generate assembly for a file
test/test_triangulation.cpp.s:
	$(MAKE) -f CMakeFiles/test_triangulation.dir/build.make CMakeFiles/test_triangulation.dir/test/test_triangulation.cpp.s
.PHONY : test/test_triangulation.cpp.s

test/test_utils.o: test/test_utils.cpp.o

.PHONY : test/test_utils.o

# target to build an object file
test/test_utils.cpp.o:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/test/test_utils.cpp.o
.PHONY : test/test_utils.cpp.o

test/test_utils.i: test/test_utils.cpp.i

.PHONY : test/test_utils.i

# target to preprocess a source file
test/test_utils.cpp.i:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/test/test_utils.cpp.i
.PHONY : test/test_utils.cpp.i

test/test_utils.s: test/test_utils.cpp.s

.PHONY : test/test_utils.s

# target to generate assembly for a file
test/test_utils.cpp.s:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/test/test_utils.cpp.s
.PHONY : test/test_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test_dbow3"
	@echo "... test_timer"
	@echo "... test_camera_model"
	@echo "... test_alignment_2d"
	@echo "... ssvo"
	@echo "... test_alignment"
	@echo "... test_pattern"
	@echo "... test_feature_detector"
	@echo "... test_utils"
	@echo "... rebuild_cache"
	@echo "... test_initializer_seq"
	@echo "... test_glog"
	@echo "... monoVO_dataset"
	@echo "... test_triangulation"
	@echo "... monoVO_live"
	@echo "... test_optimizer"
	@echo "... demo/monoVO_dataset.o"
	@echo "... demo/monoVO_dataset.i"
	@echo "... demo/monoVO_dataset.s"
	@echo "... demo/monoVO_live.o"
	@echo "... demo/monoVO_live.i"
	@echo "... demo/monoVO_live.s"
	@echo "... src/brief.o"
	@echo "... src/brief.i"
	@echo "... src/brief.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/depth_filter.o"
	@echo "... src/depth_filter.i"
	@echo "... src/depth_filter.s"
	@echo "... src/feature_alignment.o"
	@echo "... src/feature_alignment.i"
	@echo "... src/feature_alignment.s"
	@echo "... src/feature_detector.o"
	@echo "... src/feature_detector.i"
	@echo "... src/feature_detector.s"
	@echo "... src/feature_tracker.o"
	@echo "... src/feature_tracker.i"
	@echo "... src/feature_tracker.s"
	@echo "... src/frame.o"
	@echo "... src/frame.i"
	@echo "... src/frame.s"
	@echo "... src/image_alignment.o"
	@echo "... src/image_alignment.i"
	@echo "... src/image_alignment.s"
	@echo "... src/initializer.o"
	@echo "... src/initializer.i"
	@echo "... src/initializer.s"
	@echo "... src/keyframe.o"
	@echo "... src/keyframe.i"
	@echo "... src/keyframe.s"
	@echo "... src/local_mapping.o"
	@echo "... src/local_mapping.i"
	@echo "... src/local_mapping.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/map_point.o"
	@echo "... src/map_point.i"
	@echo "... src/map_point.s"
	@echo "... src/optimizer.o"
	@echo "... src/optimizer.i"
	@echo "... src/optimizer.s"
	@echo "... src/seed.o"
	@echo "... src/seed.i"
	@echo "... src/seed.s"
	@echo "... src/system.o"
	@echo "... src/system.i"
	@echo "... src/system.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/viewer.o"
	@echo "... src/viewer.i"
	@echo "... src/viewer.s"
	@echo "... test/test_alignment.o"
	@echo "... test/test_alignment.i"
	@echo "... test/test_alignment.s"
	@echo "... test/test_alignment_2d.o"
	@echo "... test/test_alignment_2d.i"
	@echo "... test/test_alignment_2d.s"
	@echo "... test/test_camera_model.o"
	@echo "... test/test_camera_model.i"
	@echo "... test/test_camera_model.s"
	@echo "... test/test_dbow3.o"
	@echo "... test/test_dbow3.i"
	@echo "... test/test_dbow3.s"
	@echo "... test/test_feature_detector.o"
	@echo "... test/test_feature_detector.i"
	@echo "... test/test_feature_detector.s"
	@echo "... test/test_glog.o"
	@echo "... test/test_glog.i"
	@echo "... test/test_glog.s"
	@echo "... test/test_initializer_seq.o"
	@echo "... test/test_initializer_seq.i"
	@echo "... test/test_initializer_seq.s"
	@echo "... test/test_optimizer.o"
	@echo "... test/test_optimizer.i"
	@echo "... test/test_optimizer.s"
	@echo "... test/test_parttern.o"
	@echo "... test/test_parttern.i"
	@echo "... test/test_parttern.s"
	@echo "... test/test_timer.o"
	@echo "... test/test_timer.i"
	@echo "... test/test_timer.s"
	@echo "... test/test_triangulation.o"
	@echo "... test/test_triangulation.i"
	@echo "... test/test_triangulation.s"
	@echo "... test/test_utils.o"
	@echo "... test/test_utils.i"
	@echo "... test/test_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

